USE module3;

insert into tags (name) values ('Dragon, komodo');
insert into tags (name) values ('Owl, madagascar hawk');
insert into tags (name) values ('Antelope, roan');
insert into tags (name) values ('Quoll, eastern');
insert into tags (name) values ('Asian lion');
insert into tags (name) values ('African jacana');
insert into tags (name) values ('Fox, silver-backed');
insert into tags (name) values ('Ass, asiatic wild');
insert into tags (name) values ('Glossy starling (unidentified)');
insert into tags (name) values ('Marmot, hoary');
insert into tags (name) values ('Square-lipped rhinoceros');
insert into tags (name) values ('Yellow mongoose');
insert into tags (name) values ('African black crake');
insert into tags (name) values ('Blue wildebeest');
insert into tags (name) values ('White-tailed jackrabbit');
insert into tags (name) values ('Bulbul, black-fronted');
insert into tags (name) values ('Fairy penguin');
insert into tags (name) values ('Mara');
insert into tags (name) values ('Otter, north american river');
insert into tags (name) values ('Palm squirrel');
insert into tags (name) values ('African fish eagle');
insert into tags (name) values ('Baboon, gelada');
insert into tags (name) values ('Wallaby, whip-tailed');
insert into tags (name) values ('Squirrel, grey-footed');
insert into tags (name) values ('Jackal, indian');
insert into tags (name) values ('White-eye, cape');
insert into tags (name) values ('Three-banded plover');
insert into tags (name) values ('Currasow (unidentified)');
insert into tags (name) values ('Glider, squirrel');
insert into tags (name) values ('Savanna fox');
insert into tags (name) values ('Civet, small-toothed palm');
insert into tags (name) values ('Bee-eater, white-fronted');
insert into tags (name) values ('Brazilian tapir');
insert into tags (name) values ('Bennett''s wallaby');
insert into tags (name) values ('Booby, blue-faced');
insert into tags (name) values ('Lorikeet, scaly-breasted');
insert into tags (name) values ('Opossum, american virginia');
insert into tags (name) values ('Pig-tailed macaque');
insert into tags (name) values ('maecenas');
insert into tags (name) values ('odio');
insert into tags (name) values ('ut');
insert into tags (name) values ('aliquam');
insert into tags (name) values ('vel');
insert into tags (name) values ('morbi');
insert into tags (name) values ('augue');
insert into tags (name) values ('semper');
insert into tags (name) values ('pellentesque');
insert into tags (name) values ('vitae');
insert into tags (name) values ('fusce');
insert into tags (name) values ('leo');
insert into tags (name) values ('sed');
insert into tags (name) values ('vestibulum');
insert into tags (name) values ('diam');
insert into tags (name) values ('lobortis');
insert into tags (name) values ('suspendisse');
insert into tags (name) values ('magnis');
insert into tags (name) values ('Plexiglass');
insert into tags (name) values ('Rubber');
insert into tags (name) values ('Glass');
insert into tags (name) values ('Plastic');
insert into tags (name) values ('Aluminum');
insert into tags (name) values ('Stone');
insert into tags (name) values ('Granite');
insert into tags (name) values ('Steel');
insert into tags (name) values ('Wood');
insert into tags (name) values ('Pink');
insert into tags (name) values ('Indigo');
insert into tags (name) values ('Puce');
insert into tags (name) values ('Violet');
insert into tags (name) values ('Red');
insert into tags (name) values ('Yellow');
insert into tags (name) values ('Aquamarine');
insert into tags (name) values ('Goldenrod');
insert into tags (name) values ('Fuscia');
insert into tags (name) values ('Maroon');
insert into tags (name) values ('Purple');
insert into tags (name) values ('Blue');
insert into tags (name) values ('Mauv');
insert into tags (name) values ('Crimson');
insert into tags (name) values ('Industrial');
insert into tags (name) values ('Outdoors');
insert into tags (name) values ('Books');
insert into tags (name) values ('Jewelry');
insert into tags (name) values ('Tools');
insert into tags (name) values ('Music');
insert into tags (name) values ('Electronics');
insert into tags (name) values ('Garden');
insert into tags (name) values ('Movies');
insert into tags (name) values ('Health');
insert into tags (name) values ('Home');
insert into tags (name) values ('Toys');
insert into tags (name) values ('Sports');
insert into tags (name) values ('Scraper');
insert into tags (name) values ('Excavator');
insert into tags (name) values ('Dragline');
insert into tags (name) values ('Bulldozer');
insert into tags (name) values ('Compactor');
insert into tags (name) values ('Backhoe');
insert into tags (name) values ('Skid-Steer');
insert into tags (name) values ('Crawler');
insert into tags (name) values ('Grader');
insert into tags (name) values ('KJI Industrial Co Ltd');
insert into tags (name) values ('CHANEL PARFUMS BEAUTE');
insert into tags (name) values ('Telestar Consulting');
insert into tags (name) values ('BioActive Nutritional, Inc.');
insert into tags (name) values ('AbbVie Inc.');
insert into tags (name) values ('NSE Products, Inc.');
insert into tags (name) values ('Kanlam');
insert into tags (name) values ('Zontrax');
insert into tags (name) values ('Stringtough');
insert into tags (name) values ('Subin');
insert into tags (name) values ('Daltfresh');
insert into tags (name) values ('Toughjoyfax');
insert into tags (name) values ('Redhold');
insert into tags (name) values ('Vagram');
insert into tags (name) values ('Viva');
insert into tags (name) values ('France');
insert into tags (name) values ('Bangladesh');
insert into tags (name) values ('China');
insert into tags (name) values ('Germany');
insert into tags (name) values ('Luxembourg');
insert into tags (name) values ('Philippines');
insert into tags (name) values ('Russia');
insert into tags (name) values ('Brazil');
insert into tags (name) values ('Vietnam');
insert into tags (name) values ('Banjar Baleagung');
insert into tags (name) values ('Penebel');
insert into tags (name) values ('Proboštov');
insert into tags (name) values ('Tambalisa');
insert into tags (name) values ('Bunog');
insert into tags (name) values ('Guariba');
insert into tags (name) values ('Chaloem Phra Kiat');
insert into tags (name) values ('Sanxi');
insert into tags (name) values ('Changqing');
insert into tags (name) values ('Silago');
insert into tags (name) values ('Draguignan');
insert into tags (name) values ('Guarapari');
insert into tags (name) values ('Bromma');
insert into tags (name) values ('Fenggao');
insert into tags (name) values ('Otradnoye');
insert into tags (name) values ('New Sibonga');
insert into tags (name) values ('Caseros');
insert into tags (name) values ('Krajan Sale');
insert into tags (name) values ('Cabreúva');
insert into tags (name) values ('Yinjiang');
insert into tags (name) values ('Albany');
insert into tags (name) values ('Guozhai');
insert into tags (name) values ('Bohicon');
insert into tags (name) values ('Umpak');
insert into tags (name) values ('Taohuajiang');
insert into tags (name) values ('Gampengrejo');
insert into tags (name) values ('Pangani');
insert into tags (name) values ('Junbu');
insert into tags (name) values ('Särevere');
insert into tags (name) values ('Göteborg');
insert into tags (name) values ('Pescadería');
insert into tags (name) values ('Tournai');
insert into tags (name) values ('Vigia');
insert into tags (name) values ('Banjarsari');
insert into tags (name) values ('Bolhrad');
insert into tags (name) values ('Kvartsitnyy');
insert into tags (name) values ('Bukal Sur');
insert into tags (name) values ('Angao');
insert into tags (name) values ('Krajan');
insert into tags (name) values ('Tanabe');
insert into tags (name) values ('Val-de-Reuil');
insert into tags (name) values ('Kuwayris Sharqī');
insert into tags (name) values ('Kiel');
insert into tags (name) values ('Paôy Pêt');
insert into tags (name) values ('Betafo');
insert into tags (name) values ('Jinji');
insert into tags (name) values ('Atolina');
insert into tags (name) values ('Hekou');
insert into tags (name) values ('Mijiang');
insert into tags (name) values ('Changsheng');
insert into tags (name) values ('La Courneuve');
insert into tags (name) values ('Bordeaux');
insert into tags (name) values ('San Guillermo');
insert into tags (name) values ('Mont-de-Marsan');
insert into tags (name) values ('Bāndarban');
insert into tags (name) values ('Yudaikelike');
insert into tags (name) values ('Viļaka');
insert into tags (name) values ('Dióni');
insert into tags (name) values ('la Massana');
insert into tags (name) values ('Kedungbulu');
insert into tags (name) values ('Fier');
insert into tags (name) values ('Voronkov');
insert into tags (name) values ('Mafa');
insert into tags (name) values ('Pôsto Fiscal Rolim de Moura');
insert into tags (name) values ('Leipzig');
insert into tags (name) values ('Burgas');
insert into tags (name) values ('Vřesina');
insert into tags (name) values ('Nanganumba');
insert into tags (name) values ('La Maná');
insert into tags (name) values ('Safonovo');
insert into tags (name) values ('Tāybād');
insert into tags (name) values ('El Porvenir');
insert into tags (name) values ('Chengxi');
insert into tags (name) values ('Angus');
insert into tags (name) values ('Vodňany');
insert into tags (name) values ('Tuochuan');
insert into tags (name) values ('Burns Lake');
insert into tags (name) values ('Lampa');
insert into tags (name) values ('Laikit, Laikit II (Dimembe)');
insert into tags (name) values ('Dakhla');
insert into tags (name) values ('Bendungan');
insert into tags (name) values ('Dadaha');
insert into tags (name) values ('Kiuruvesi');
insert into tags (name) values ('Shuigou');
insert into tags (name) values ('Salimbao');
insert into tags (name) values ('Houjia');
insert into tags (name) values ('Charata');
insert into tags (name) values ('Lañgub');
insert into tags (name) values ('Ostankinskiy');
insert into tags (name) values ('Bangassou');
insert into tags (name) values ('Ivanovo');
insert into tags (name) values ('Lennec');
insert into tags (name) values ('Dadong');
insert into tags (name) values ('Mangaldan');
insert into tags (name) values ('Bacem');
insert into tags (name) values ('Tlogotunggal');
insert into tags (name) values ('Melissochóri');
insert into tags (name) values ('Faaa');
insert into tags (name) values ('Krajanjugosari');
insert into tags (name) values ('Nato');
insert into tags (name) values ('Sacahuista');
insert into tags (name) values ('Lynge''s Navel Lichen');
insert into tags (name) values ('Orthotrichum Moss');
insert into tags (name) values ('Smooth Fanpetals');
insert into tags (name) values ('Trailing Pearlwort');
insert into tags (name) values ('Orange Lichen');
insert into tags (name) values ('North Fork Heartleaf');
insert into tags (name) values ('Braun''s Rockcress');
insert into tags (name) values ('Brown Beaksedge');
insert into tags (name) values ('Japanese Climbing Fern');
insert into tags (name) values ('Dust Lichen');
insert into tags (name) values ('American Water Starwort');
insert into tags (name) values ('Coral Dropseed');
insert into tags (name) values ('Rice Bean');
insert into tags (name) values ('Sanddune Ipomopsis');
insert into tags (name) values ('Lanceleaf Springbeauty');
insert into tags (name) values ('Guatemalan Avocado');
insert into tags (name) values ('Virgin Island Passionflower');
insert into tags (name) values ('Field Pepperweed');
insert into tags (name) values ('Disc Lichen');
insert into tags (name) values ('Rocky Mountain Blazing Star');
insert into tags (name) values ('Dahoon');
insert into tags (name) values ('Sweetscented Biscuitroot');
insert into tags (name) values ('Retama');
insert into tags (name) values ('Sagebrush Buttercup');
insert into tags (name) values ('Clidemia');
insert into tags (name) values ('Watson''s Brickellbush');
insert into tags (name) values ('Torrey''s Penstemon');
insert into tags (name) values ('American Beakgrain');
insert into tags (name) values ('California Broomrape');
insert into tags (name) values ('Mt. Tamalpais Jewelflower');
insert into tags (name) values ('Nepsera');
insert into tags (name) values ('Crabgrass');
insert into tags (name) values ('Dubautia');
insert into tags (name) values ('Whorled Milkwort');
insert into tags (name) values ('Sweet Orange');
insert into tags (name) values ('Fiddleneck');
insert into tags (name) values ('Loblolly Pine');
insert into tags (name) values ('Great Basin Brome');
insert into tags (name) values ('White Fringed Orchid');
insert into tags (name) values ('Tapertip Desertparsley');
insert into tags (name) values ('Thinleaf Sunflower');
insert into tags (name) values ('Timopheev''s Wheat');
insert into tags (name) values ('Bolinas Manzanita');
insert into tags (name) values ('White Rubber Vine');
insert into tags (name) values ('Waxflower Shinleaf');
insert into tags (name) values ('Spike Fescue');
insert into tags (name) values ('Graceful Hawthorn');
insert into tags (name) values ('Suksdorf''s Large Camas');
insert into tags (name) values ('Proliferating Bulrush');
insert into tags (name) values ('Sharpleaf St. Johnswort');
insert into tags (name) values ('Kruckeberg''s Hollyfern');
insert into tags (name) values ('Stickystem Penstemon');
insert into tags (name) values ('Siberian Wallflower');
insert into tags (name) values ('Gland Indian Paintbrush');
insert into tags (name) values ('Whitethorn Acacia');
insert into tags (name) values ('Feather River Monardella');
insert into tags (name) values ('Slender Sandbur');
insert into tags (name) values ('Sonoran Silverbush');
insert into tags (name) values ('Santa Rita Threeawn');
insert into tags (name) values ('Djave');
insert into tags (name) values ('Hybrid Locust');
insert into tags (name) values ('Green Orchid');
insert into tags (name) values ('Gypsum Phacelia');
insert into tags (name) values ('Binjai');
insert into tags (name) values ('Softhair Marbleseed');
insert into tags (name) values ('Chapman''s Crownbeard');
insert into tags (name) values ('Small-leaf Arrowwood');
insert into tags (name) values ('Kaweah Brodiaea');
insert into tags (name) values ('Red Dome Blanketflower');
insert into tags (name) values ('Garden Lettuce');
insert into tags (name) values ('Amygdalaria Lichen');
insert into tags (name) values ('Devil''s Bite');
insert into tags (name) values ('Smallflower Lupine');
insert into tags (name) values ('Athelia Lichen');
insert into tags (name) values ('Tropical Spiderflower');
insert into tags (name) values ('Congdon''s Lewisia');
insert into tags (name) values ('Hairy New York Aster');
insert into tags (name) values ('Kaibab Spinystar');
insert into tags (name) values ('Zamia');
insert into tags (name) values ('Maui Dubautia');
insert into tags (name) values ('Mountain Pride');
insert into tags (name) values ('Cusick''s Beardtongue');
insert into tags (name) values ('Lava Dubautia');
insert into tags (name) values ('Cottonrose');
insert into tags (name) values ('Argentine Senna');
insert into tags (name) values ('Nelson''s Brickellbush');
insert into tags (name) values ('Dwarf Pepperweed');
insert into tags (name) values ('Cobralily');
insert into tags (name) values ('Gray''s Seablush');
insert into tags (name) values ('European Beech');
insert into tags (name) values ('Tube Lichen');
insert into tags (name) values ('Rocky Mountain Fescue');
insert into tags (name) values ('Arctic Cinquefoil');
insert into tags (name) values ('Howell''s Quillwort');
insert into tags (name) values ('Seaport Goosefoot');
insert into tags (name) values ('Higuillo De Hoja Menuda');
insert into tags (name) values ('Allen Springs Dwarf-flax');
insert into tags (name) values ('Malcolmia');
insert into tags (name) values ('Hernando County Noddingcaps');
insert into tags (name) values ('Valerianaceae');
insert into tags (name) values ('Rubiaceae');
insert into tags (name) values ('Splachnaceae');
insert into tags (name) values ('Hydrophyllaceae');
insert into tags (name) values ('Uncertain Ascomycota Family');
insert into tags (name) values ('Paeoniaceae');
insert into tags (name) values ('Fabaceae');
insert into tags (name) values ('Elaeocarpaceae');
insert into tags (name) values ('Brassicaceae');
insert into tags (name) values ('Asteraceae');
insert into tags (name) values ('Parmeliaceae');
insert into tags (name) values ('Scrophulariaceae');
insert into tags (name) values ('Rutaceae');
insert into tags (name) values ('Funariaceae');
insert into tags (name) values ('Poaceae');
insert into tags (name) values ('Hamamelidaceae');
insert into tags (name) values ('Capparaceae');
insert into tags (name) values ('Convolvulaceae');
insert into tags (name) values ('Solanaceae');
insert into tags (name) values ('Fagaceae');
insert into tags (name) values ('Caprifoliaceae');
insert into tags (name) values ('Juncaceae');
insert into tags (name) values ('Lycopodiaceae');
insert into tags (name) values ('Campanulaceae');
insert into tags (name) values ('Callitrichaceae');
insert into tags (name) values ('Amaranthaceae');
insert into tags (name) values ('Malvaceae');
insert into tags (name) values ('Thelypteridaceae');
insert into tags (name) values ('Leskeaceae');
insert into tags (name) values ('Rhamnaceae');
insert into tags (name) values ('Boraginaceae');
insert into tags (name) values ('Dactylosporaceae');
insert into tags (name) values ('Physciaceae');
insert into tags (name) values ('Cyperaceae');
insert into tags (name) values ('Liliaceae');
insert into tags (name) values ('Rosaceae');
insert into tags (name) values ('Violaceae');
insert into tags (name) values ('Verbenaceae');
insert into tags (name) values ('Papaveraceae');
insert into tags (name) values ('Pinaceae');
insert into tags (name) values ('Fumariaceae');
insert into tags (name) values ('Nymphaeaceae');
insert into tags (name) values ('Pteridaceae');
insert into tags (name) values ('Collemataceae');
insert into tags (name) values ('Amblystegiaceae');
insert into tags (name) values ('Fissidentaceae');
insert into tags (name) values ('Betulaceae');
insert into tags (name) values ('Euphorbiaceae');
insert into tags (name) values ('Cucurbitaceae');
insert into tags (name) values ('Lecanoraceae');
insert into tags (name) values ('Clusiaceae');
insert into tags (name) values ('Lamiaceae');
insert into tags (name) values ('Aristolochiaceae');
insert into tags (name) values ('Sapindaceae');
insert into tags (name) values ('Plantaginaceae');
insert into tags (name) values ('Marantaceae');
insert into tags (name) values ('local');
insert into tags (name) values ('system-worthy');
insert into tags (name) values ('Adaptive');
insert into tags (name) values ('Multi-layered');
insert into tags (name) values ('workforce');
insert into tags (name) values ('Integrated');
insert into tags (name) values ('process improvement');
insert into tags (name) values ('Right-sized');
insert into tags (name) values ('6th generation');
insert into tags (name) values ('Grass-roots');
insert into tags (name) values ('Diverse');
insert into tags (name) values ('secured line');
insert into tags (name) values ('Exclusive');
insert into tags (name) values ('web-enabled');
insert into tags (name) values ('policy');
insert into tags (name) values ('Profit-focused');
insert into tags (name) values ('responsive');
insert into tags (name) values ('groupware');
insert into tags (name) values ('optimal');
insert into tags (name) values ('exuding');
insert into tags (name) values ('capacity');
insert into tags (name) values ('circuit');
insert into tags (name) values ('web');
insert into tags (name) values ('Ameliorated');
insert into tags (name) values ('application');
insert into tags (name) values ('capability');
insert into tags (name) values ('multi-tasking');
insert into tags (name) values ('methodology');
insert into tags (name) values ('optimizing');
insert into tags (name) values ('database');
insert into tags (name) values ('fault-tolerant');
insert into tags (name) values ('tertiary');
insert into tags (name) values ('challenge');
insert into tags (name) values ('projection');
insert into tags (name) values ('benchmark');
insert into tags (name) values ('asynchronous');
insert into tags (name) values ('national');
insert into tags (name) values ('toolset');
insert into tags (name) values ('fresh-thinking');
insert into tags (name) values ('methodical');
insert into tags (name) values ('Realigned');
insert into tags (name) values ('5th generation');
insert into tags (name) values ('pricing structure');
insert into tags (name) values ('systemic');
insert into tags (name) values ('full-range');
insert into tags (name) values ('framework');
insert into tags (name) values ('zero tolerance');
insert into tags (name) values ('Reactive');
insert into tags (name) values ('collaboration');
insert into tags (name) values ('data-warehouse');
insert into tags (name) values ('Total');
insert into tags (name) values ('Persistent');
insert into tags (name) values ('maximized');
insert into tags (name) values ('object-oriented');
insert into tags (name) values ('model');
insert into tags (name) values ('parallelism');
insert into tags (name) values ('grid-enabled');
insert into tags (name) values ('Distributed');
insert into tags (name) values ('Stand-alone');
insert into tags (name) values ('Synergistic');
insert into tags (name) values ('disintermediate');
insert into tags (name) values ('Multi-channelled');
insert into tags (name) values ('Centralized');
insert into tags (name) values ('Up-sized');
insert into tags (name) values ('Seamless');
insert into tags (name) values ('zero administration');
insert into tags (name) values ('standardization');
insert into tags (name) values ('uniform');
insert into tags (name) values ('Extended');
insert into tags (name) values ('incremental');
insert into tags (name) values ('archive');
insert into tags (name) values ('logistical');
insert into tags (name) values ('eco-centric');
insert into tags (name) values ('neutral');
insert into tags (name) values ('Streamlined');
insert into tags (name) values ('utilisation');
insert into tags (name) values ('hardware');
insert into tags (name) values ('tangible');
insert into tags (name) values ('dedicated');
insert into tags (name) values ('Intuitive');
insert into tags (name) values ('monitoring');
insert into tags (name) values ('Organic');
insert into tags (name) values ('Zoomdog');
insert into tags (name) values ('Tazz');
insert into tags (name) values ('Zoonoodle');
insert into tags (name) values ('Fivebridge');
insert into tags (name) values ('Skipstorm');
insert into tags (name) values ('Blogtag');
insert into tags (name) values ('Twitterlist');
insert into tags (name) values ('Rhynyx');
insert into tags (name) values ('Browsezoom');
insert into tags (name) values ('Edgeblab');
insert into tags (name) values ('Camido');
insert into tags (name) values ('Oyoloo');
insert into tags (name) values ('Katz');
insert into tags (name) values ('Kayveo');
insert into tags (name) values ('Mybuzz');
insert into tags (name) values ('Nlounge');
insert into tags (name) values ('Mita');
insert into tags (name) values ('Meetz');
insert into tags (name) values ('Vitz');
insert into tags (name) values ('Topiclounge');
insert into tags (name) values ('Reallinks');
insert into tags (name) values ('Oyoba');
insert into tags (name) values ('Blognation');
insert into tags (name) values ('Aivee');
insert into tags (name) values ('Twitterwire');
insert into tags (name) values ('Devpoint');
insert into tags (name) values ('Plajo');
insert into tags (name) values ('Jabbersphere');
insert into tags (name) values ('Buzzbean');
insert into tags (name) values ('Fivespan');
insert into tags (name) values ('Trilia');
insert into tags (name) values ('Skinte');
insert into tags (name) values ('Brainsphere');
insert into tags (name) values ('Realcube');
insert into tags (name) values ('Eayo');
insert into tags (name) values ('Skimia');
insert into tags (name) values ('Eamia');
insert into tags (name) values ('Skilith');
insert into tags (name) values ('Abatz');
insert into tags (name) values ('Voonix');
insert into tags (name) values ('Kare');
insert into tags (name) values ('Yakitri');
insert into tags (name) values ('Chatterpoint');
insert into tags (name) values ('Mudo');
insert into tags (name) values ('Quimba');
insert into tags (name) values ('Kwilith');
insert into tags (name) values ('Meemm');
insert into tags (name) values ('Skivee');
insert into tags (name) values ('Meedoo');
insert into tags (name) values ('Twiyo');
insert into tags (name) values ('Trudeo');
insert into tags (name) values ('Pixoboo');
insert into tags (name) values ('LiveZ');
insert into tags (name) values ('Twinte');
insert into tags (name) values ('Zoonder');
insert into tags (name) values ('Innotype');
insert into tags (name) values ('Quamba');
insert into tags (name) values ('Skaboo');
insert into tags (name) values ('Oyope');
insert into tags (name) values ('Photospace');
insert into tags (name) values ('Oyonder');
insert into tags (name) values ('Meevee');
insert into tags (name) values ('Riffpath');
insert into tags (name) values ('Gigaclub');
insert into tags (name) values ('Wordware');
insert into tags (name) values ('Edgetag');
insert into tags (name) values ('InnoZ');
insert into tags (name) values ('Avavee');
insert into tags (name) values ('Jaxnation');
insert into tags (name) values ('Tanoodle');
insert into tags (name) values ('Gabcube');
insert into tags (name) values ('Babblestorm');
insert into tags (name) values ('Devbug');
insert into tags (name) values ('Yozio');
insert into tags (name) values ('Quimm');
insert into tags (name) values ('Livepath');
insert into tags (name) values ('Topiczoom');
insert into tags (name) values ('Quatz');
insert into tags (name) values ('Brainbox');
insert into tags (name) values ('Wordpedia');
insert into tags (name) values ('Yoveo');
insert into tags (name) values ('Skinder');
insert into tags (name) values ('Thoughtsphere');
insert into tags (name) values ('Mydo');
insert into tags (name) values ('Flipstorm');
insert into tags (name) values ('Photobug');
insert into tags (name) values ('Albanian');
insert into tags (name) values ('Finnish');
insert into tags (name) values ('Norwegian');
insert into tags (name) values ('Dhivehi');
insert into tags (name) values ('Maltese');
insert into tags (name) values ('Nicaraguan');
insert into tags (name) values ('South American');
insert into tags (name) values ('Costa Rican');
insert into tags (name) values ('Malaysian');
insert into tags (name) values ('Keyboardist');
insert into tags (name) values ('Yard Work');
insert into tags (name) values ('CSPro');
insert into tags (name) values ('OSHA Instruction');
insert into tags (name) values ('IRAs');
insert into tags (name) values ('FHA');
insert into tags (name) values ('LPR');
insert into tags (name) values ('RTU');
insert into tags (name) values ('VHDL-AMS');
insert into tags (name) values ('Mobile Communications');
insert into tags (name) values ('Oracle Applications');
insert into tags (name) values ('Small Business Marketing');
insert into tags (name) values ('Yield');
insert into tags (name) values ('GCP');
insert into tags (name) values ('MPLS VPN');
insert into tags (name) values ('Tax Accounting');
insert into tags (name) values ('CGI scripts');
insert into tags (name) values ('Test Automation');
insert into tags (name) values ('Global Business Development');
insert into tags (name) values ('Nintex');
insert into tags (name) values ('JUNOS');
insert into tags (name) values ('IATA');
insert into tags (name) values ('Zoo');
insert into tags (name) values ('Xpress');
insert into tags (name) values ('Klarity');
insert into tags (name) values ('Digital Signal Processors');
insert into tags (name) values ('Award Submissions');
insert into tags (name) values ('Legal Liability');
insert into tags (name) values ('HLSL');
insert into tags (name) values ('Commercial Aviation');
insert into tags (name) values ('AED');
insert into tags (name) values ('Lesson Planning');
insert into tags (name) values ('Water Features');
insert into tags (name) values ('American Politics');
insert into tags (name) values ('HR Transformation');
insert into tags (name) values ('DFA');
insert into tags (name) values ('Newsletters');
insert into tags (name) values ('Google Webmaster Tools');
insert into tags (name) values ('GSA Schedule');
insert into tags (name) values ('SRT');
insert into tags (name) values ('Twilio');
insert into tags (name) values ('Juvederm');
insert into tags (name) values ('RCSA');
insert into tags (name) values ('VBScript');
insert into tags (name) values ('Wufoo');
insert into tags (name) values ('PgSQL');
insert into tags (name) values ('FFE');
insert into tags (name) values ('Knee');
insert into tags (name) values ('Eggplant');
insert into tags (name) values ('Aqualogic');
insert into tags (name) values ('NCIE');
insert into tags (name) values ('Aspen HYSYS');
insert into tags (name) values ('EViews');
insert into tags (name) values ('ODI');
insert into tags (name) values ('Substance Use Disorders');
insert into tags (name) values ('Sweaters');
insert into tags (name) values ('KPI Reports');
insert into tags (name) values ('Microsoft Dynamics NAV');
insert into tags (name) values ('Abaqus');
insert into tags (name) values ('Screenwriting');
insert into tags (name) values ('Powder X-ray Diffraction');
insert into tags (name) values ('RTI');
insert into tags (name) values ('Job Descriptions');
insert into tags (name) values ('FSMS');
insert into tags (name) values ('CCIM');
insert into tags (name) values ('VLAN');
insert into tags (name) values ('BLS');
insert into tags (name) values ('SMS');
insert into tags (name) values ('Visual Basic');
insert into tags (name) values ('DDoS Mitigation');
insert into tags (name) values ('ADP Payroll');
insert into tags (name) values ('SG&amp;A');
insert into tags (name) values ('DV');
insert into tags (name) values ('Yellow Book');
insert into tags (name) values ('Ektron');
insert into tags (name) values ('CQ');
insert into tags (name) values ('EELS');
insert into tags (name) values ('ISDN');
insert into tags (name) values ('Oil Analysis');
insert into tags (name) values ('HCS');
insert into tags (name) values ('RHEV');
insert into tags (name) values ('Zoology');
insert into tags (name) values ('DVD');
insert into tags (name) values ('Xero');
insert into tags (name) values ('VTC');
insert into tags (name) values ('Utilization Review');
insert into tags (name) values ('Strategic Sourcing');
insert into tags (name) values ('VSE');
insert into tags (name) values ('Avid Xpress');
insert into tags (name) values ('Daily');
insert into tags (name) values ('Monthly');
insert into tags (name) values ('Often');
insert into tags (name) values ('Seldom');
insert into tags (name) values ('LSXMK');
insert into tags (name) values ('ESG');
insert into tags (name) values ('VKTXW');
insert into tags (name) values ('PGH');
insert into tags (name) values ('BRKR');
insert into tags (name) values ('JLS');
insert into tags (name) values ('WPM');
insert into tags (name) values ('MEI');
insert into tags (name) values ('MMU');
insert into tags (name) values ('TEDU');
insert into tags (name) values ('FFNW');
insert into tags (name) values ('DXCM');
insert into tags (name) values ('CVE');
insert into tags (name) values ('SAR');
insert into tags (name) values ('FI');
insert into tags (name) values ('NW^C');
insert into tags (name) values ('NLST');
insert into tags (name) values ('PTX');
insert into tags (name) values ('GPIA');
insert into tags (name) values ('SOL');
insert into tags (name) values ('AHT^G');
insert into tags (name) values ('MTB^');
insert into tags (name) values ('IART');
insert into tags (name) values ('CASI');
insert into tags (name) values ('ROKA');
insert into tags (name) values ('NYMT');
insert into tags (name) values ('CEMI');
insert into tags (name) values ('MTBCP');
insert into tags (name) values ('PN');
insert into tags (name) values ('MVCB');
insert into tags (name) values ('Property-Casualty Insurers');
insert into tags (name) values ('Hospital/Nursing Management');
insert into tags (name) values ('Catalog/Specialty Distribution');
insert into tags (name) values ('Building Products');
insert into tags (name) values ('phasellus');
insert into tags (name) values ('sapien');
insert into tags (name) values ('nisi volutpat');
insert into tags (name) values ('consectetuer adipiscing');
insert into tags (name) values ('nullam sit');
insert into tags (name) values ('accumsan felis');
insert into tags (name) values ('turpis integer');
insert into tags (name) values ('duis');
insert into tags (name) values ('euismod');
insert into tags (name) values ('id ornare');
insert into tags (name) values ('enim leo');
insert into tags (name) values ('ipsum dolor');
insert into tags (name) values ('tortor');
insert into tags (name) values ('purus');
insert into tags (name) values ('augue aliquam');
insert into tags (name) values ('eu nibh');
insert into tags (name) values ('felis');
insert into tags (name) values ('et');
insert into tags (name) values ('pede lobortis');
insert into tags (name) values ('in');
insert into tags (name) values ('potenti');
insert into tags (name) values ('ipsum');
insert into tags (name) values ('vestibulum ac');
insert into tags (name) values ('true');
insert into tags (name) values ('false');
insert into tags (name) values ('bankcard');
insert into tags (name) values ('diners-club-enroute');
insert into tags (name) values ('jcb');
insert into tags (name) values ('china-unionpay');
insert into tags (name) values ('maestro');
insert into tags (name) values ('laser');
insert into tags (name) values ('switch');
insert into tags (name) values ('Won');
insert into tags (name) values ('Rupiah');
insert into tags (name) values ('Franc');
insert into tags (name) values ('Real');
insert into tags (name) values ('Shilling');
insert into tags (name) values ('Electrical');
insert into tags (name) values ('Site Furnishings');
insert into tags (name) values ('Anastrozole');
insert into tags (name) values ('Baclofen');
insert into tags (name) values ('Ery-Ped');
insert into tags (name) values ('Prednisone');
insert into tags (name) values ('Stool Softener');
insert into tags (name) values ('Olive Pollen');
insert into tags (name) values ('Blistex');
insert into tags (name) values ('Glyburide');
insert into tags (name) values ('Scallop');
insert into tags (name) values ('nhs.uk');
insert into tags (name) values ('mail.ru');
insert into tags (name) values ('acquirethisname.com');
insert into tags (name) values ('reverbnation.com');
insert into tags (name) values ('ebay.co.uk');
insert into tags (name) values ('msn.com');
insert into tags (name) values ('google.com.br');
insert into tags (name) values ('washingtonpost.com');
insert into tags (name) values ('google.fr');
insert into tags (name) values ('cam.ac.uk');
insert into tags (name) values ('ihg.com');
insert into tags (name) values ('senate.gov');
insert into tags (name) values ('auda.org.au');
insert into tags (name) values ('disqus.com');
insert into tags (name) values ('zdnet.com');
insert into tags (name) values ('example.com');
insert into tags (name) values ('hao123.com');
insert into tags (name) values ('jugem.jp');
insert into tags (name) values ('flickr.com');
insert into tags (name) values ('who.int');
insert into tags (name) values ('parallels.com');
insert into tags (name) values ('aboutads.info');
insert into tags (name) values ('ox.ac.uk');
insert into tags (name) values ('harvard.edu');
insert into tags (name) values ('stanford.edu');
insert into tags (name) values ('digg.com');
insert into tags (name) values ('issuu.com');
insert into tags (name) values ('devhub.com');
insert into tags (name) values ('toplist.cz');
insert into tags (name) values ('bizjournals.com');
insert into tags (name) values ('8.2');
insert into tags (name) values ('1.9');
insert into tags (name) values ('6.5.8');
insert into tags (name) values ('9.9');
insert into tags (name) values ('0.91');
insert into tags (name) values ('7.4');
insert into tags (name) values ('3.2');
insert into tags (name) values ('6.2.9');
insert into tags (name) values ('1.8');
insert into tags (name) values ('0.82');
insert into tags (name) values ('4.56');
insert into tags (name) values ('4.2');
insert into tags (name) values ('0.6.3');
insert into tags (name) values ('0.8.0');
insert into tags (name) values ('5.43');
insert into tags (name) values ('0.10');
insert into tags (name) values ('5.6.4');
insert into tags (name) values ('0.3.3');
insert into tags (name) values ('8.46');
insert into tags (name) values ('4.8');
insert into tags (name) values ('6.31');
insert into tags (name) values ('0.79');
insert into tags (name) values ('0.6.6');
insert into tags (name) values ('6.5.1');
insert into tags (name) values ('0.4.4');
insert into tags (name) values ('0.9.7');
insert into tags (name) values ('9.11');
insert into tags (name) values ('0.5.0');
insert into tags (name) values ('2.42');
insert into tags (name) values ('4.22');
insert into tags (name) values ('Greenlam');
insert into tags (name) values ('Bitchip');
insert into tags (name) values ('Alphazap');
insert into tags (name) values ('Aerified');
insert into tags (name) values ('Alpha');
insert into tags (name) values ('Konklux');
insert into tags (name) values ('Latlux');
insert into tags (name) values ('Zoolab');
insert into tags (name) values ('Span');
insert into tags (name) values ('Voyatouch');
insert into tags (name) values ('Holdlamis');
insert into tags (name) values ('Otcom');
insert into tags (name) values ('Lotlux');
insert into tags (name) values ('Bitwolf');
insert into tags (name) values ('Flowdesk');
insert into tags (name) values ('Biodex');
insert into tags (name) values ('ikenaway0');
insert into tags (name) values ('mruppelin1');
insert into tags (name) values ('egrabb2');
insert into tags (name) values ('tdionisi3');
insert into tags (name) values ('gleeming4');
insert into tags (name) values ('mdrysdell5');
insert into tags (name) values ('labry6');
insert into tags (name) values ('dogborne7');
insert into tags (name) values ('dkerfut8');
insert into tags (name) values ('nkiezler9');
insert into tags (name) values ('mfewlessa');
insert into tags (name) values ('ojosefsohnb');
insert into tags (name) values ('frouthornc');
insert into tags (name) values ('kcyplerd');
insert into tags (name) values ('meyckele');
insert into tags (name) values ('mhendrenf');
insert into tags (name) values ('aowerg');
insert into tags (name) values ('rlamboth');
insert into tags (name) values ('dsutchi');
insert into tags (name) values ('mdemendozaj');
insert into tags (name) values ('sthowlessk');
insert into tags (name) values ('jgauntl');
insert into tags (name) values ('rmcasterm');
insert into tags (name) values ('gabendrothn');
insert into tags (name) values ('blittlefairo');
insert into tags (name) values ('cgrimsdithp');
insert into tags (name) values ('ysuggettq');
insert into tags (name) values ('dgrastyer');
insert into tags (name) values ('abrimblecombs');
insert into tags (name) values ('etorrisit');
insert into tags (name) values ('cdenson0');
insert into tags (name) values ('mdelafont1');
insert into tags (name) values ('amirrlees2');
insert into tags (name) values ('ifrill3');
insert into tags (name) values ('wkersey4');
insert into tags (name) values ('citzcovich5');
insert into tags (name) values ('diowarch6');
insert into tags (name) values ('zsilvermann7');
insert into tags (name) values ('kkezar8');
insert into tags (name) values ('mbellison9');
insert into tags (name) values ('zellerkera');
insert into tags (name) values ('gduffittb');
insert into tags (name) values ('bperrinchiefc');
insert into tags (name) values ('vciobotarod');
insert into tags (name) values ('afarlambe');
insert into tags (name) values ('balkinf');
insert into tags (name) values ('oquartermaing');
insert into tags (name) values ('drearyh');
insert into tags (name) values ('aloydi');
insert into tags (name) values ('wbonhillj');
insert into tags (name) values ('idymidowskik');
insert into tags (name) values ('jpendridl');
insert into tags (name) values ('abeckem');
insert into tags (name) values ('ctrayfordn');
insert into tags (name) values ('mbarbosao');
insert into tags (name) values ('ashakesbyp');
insert into tags (name) values ('tbentsonq');
insert into tags (name) values ('btaskerr');
insert into tags (name) values ('aprattes');
insert into tags (name) values ('rrudramt');
insert into tags (name) values ('rbrine1');
insert into tags (name) values ('sdechelette2');
insert into tags (name) values ('jkerner3');
insert into tags (name) values ('jforo4');
insert into tags (name) values ('ccheetham5');
insert into tags (name) values ('tmacsharry6');
insert into tags (name) values ('bnovotni7');
insert into tags (name) values ('kjockle8');
insert into tags (name) values ('jfalvey9');
insert into tags (name) values ('wschoolinga');
insert into tags (name) values ('rhamsleyb');
insert into tags (name) values ('kbartolinic');
insert into tags (name) values ('eprobetd');
insert into tags (name) values ('cwellesleye');
insert into tags (name) values ('jdreganf');
insert into tags (name) values ('tdedenhamg');
insert into tags (name) values ('jgilleanh');
insert into tags (name) values ('aroughti');
insert into tags (name) values ('llivingstonj');
insert into tags (name) values ('bcuxonk');
insert into tags (name) values ('wboolsenl');
insert into tags (name) values ('ffilippazzom');
insert into tags (name) values ('erendern');
insert into tags (name) values ('gwelleno');
insert into tags (name) values ('tcattonp');
insert into tags (name) values ('edu');
insert into tags (name) values ('com');
insert into tags (name) values ('org');
insert into tags (name) values ('mil');
insert into tags (name) values ('video/x-mpeg');
insert into tags (name) values ('application/vnd.ms-powerpoint');
insert into tags (name) values ('video/msvideo');
insert into tags (name) values ('image/pjpeg');
insert into tags (name) values ('image/x-tiff');
insert into tags (name) values ('application/excel');
insert into tags (name) values ('image/gif');
insert into tags (name) values ('text/plain');
insert into tags (name) values ('image/tiff');
insert into tags (name) values ('application/x-excel');
insert into tags (name) values ('image/png');
insert into tags (name) values ('application/x-msexcel');
insert into tags (name) values ('application/pdf');
insert into tags (name) values ('application/msword');
insert into tags (name) values ('application/mspowerpoint');
insert into tags (name) values ('Avenue');
insert into tags (name) values ('Junction');
insert into tags (name) values ('Alley');
insert into tags (name) values ('Point');
insert into tags (name) values ('Park');
insert into tags (name) values ('Circle');
insert into tags (name) values ('Hill');
insert into tags (name) values ('Crossing');
insert into tags (name) values ('Way');
insert into tags (name) values ('Netishyn');
insert into tags (name) values ('Santa Maria');
insert into tags (name) values ('Liangshuijing');
insert into tags (name) values ('Guxi');
insert into tags (name) values ('Yaguaraparo');
insert into tags (name) values ('Liulimiao');
insert into tags (name) values ('Milton');
insert into tags (name) values ('Kochevo');
insert into tags (name) values ('Áno Liósia');
insert into tags (name) values ('Pecka');
insert into tags (name) values ('Kizil');
insert into tags (name) values ('Dongda');
insert into tags (name) values ('Santarém');
insert into tags (name) values ('Bang Phlat');
insert into tags (name) values ('Sydney');
insert into tags (name) values ('Hồ Xá');
insert into tags (name) values ('Xazgat');
insert into tags (name) values ('Båstad');
insert into tags (name) values ('Sabaneta');
insert into tags (name) values ('Sampaloc');
insert into tags (name) values ('Umi');
insert into tags (name) values ('Blang Dalam');
insert into tags (name) values ('Otradnaya');
insert into tags (name) values ('Dolní Cerekev');
insert into tags (name) values ('San Juan');
insert into tags (name) values ('Zamarski');
insert into tags (name) values ('Ribeirão');
insert into tags (name) values ('Tarikolot');
insert into tags (name) values ('Chemnitz');
insert into tags (name) values ('Espinosa');
insert into tags (name) values ('Rugby Union');
insert into tags (name) values ('Piano Education');
insert into tags (name) values ('Feature Articles');
insert into tags (name) values ('iPhone');
insert into tags (name) values ('Cultural Awareness');
insert into tags (name) values ('New Urbanism');
insert into tags (name) values ('Office Administration');
insert into tags (name) values ('uDig');
insert into tags (name) values ('Legal Documents');
insert into tags (name) values ('Jewish Studies');
insert into tags (name) values ('DH+');
insert into tags (name) values ('IBC');
insert into tags (name) values ('PKMS');
insert into tags (name) values ('SSD');
insert into tags (name) values ('TMJ Dysfunction');
insert into tags (name) values ('End User Training');
insert into tags (name) values ('Kaizen Leadership');
insert into tags (name) values ('OJEU');
insert into tags (name) values ('IEP');
insert into tags (name) values ('XQuery');
insert into tags (name) values ('EFQM Excellence Model');
insert into tags (name) values ('Globalization');
insert into tags (name) values ('Client Relations');
insert into tags (name) values ('DFX');
insert into tags (name) values ('PK/PD');
insert into tags (name) values ('GDS systems');
insert into tags (name) values ('Performance Tuning');
insert into tags (name) values ('Blackberry OS');
insert into tags (name) values ('FBT');
insert into tags (name) values ('Pitching Ideas');
insert into tags (name) values ('xCP');
insert into tags (name) values ('JBA');
insert into tags (name) values ('Multilingual');
insert into tags (name) values ('BTO');
insert into tags (name) values ('HMDA');
insert into tags (name) values ('Grant Writing');
insert into tags (name) values ('XFS');
insert into tags (name) values ('Family Law');
insert into tags (name) values ('Gstreamer');
insert into tags (name) values ('EZ Labor');
insert into tags (name) values ('XFire');
insert into tags (name) values ('Athletic Performance');
insert into tags (name) values ('xSeries');
insert into tags (name) values ('Eclipse');
insert into tags (name) values ('Rooms Division');
insert into tags (name) values ('RS485');
insert into tags (name) values ('Kronos WFC');
insert into tags (name) values ('Experion PKS');
